insert into Location( Name, Sid) values('Bahrain',0);
insert into Location( Name, Sid) values('Manama',1);
insert into Location( Name, Sid) values('Isa Town',1);
insert into Location( Name, Sid) values('Block 100',2);
insert into Location( Name, Sid) values( 'Block 101',2);
insert into Location( Name, Sid) values( 'Block 202',3);
insert into Location( Name, Sid) values( 'Block 209',3);
insert into Location( Name, Sid) values( 'Street 1',4);
insert into Location( Name, Sid) values( 'Street 2',5);
insert into Location( Name, Sid) values('Street 3',6);
insert into Location( Name, Sid) values('Street 4',7);
insert into Location( Name, Sid) values('Building 10',8);
insert into Location( Name, Sid) values('Building 20',8);
insert into Location( Name, Sid) values('Building 30',9);
insert into Location( Name, Sid) values('Building 40',9);
insert into Location( Name, Sid) values('Building 50',10);
insert into Location( Name, Sid) values('Building 60',10);
insert into Location( Name, Sid) values('Building 70',11);
insert into Location( Name, Sid) values('Building 80',11);