
insert into [Service]   values ('structure', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into [Service]   values ('multi-tasking', 'Mauris sit amet eros.');
insert into [Service]   values ('Self-enabling', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into [Service]   values ('Cross-platform', 'Quisque ut erat.');
insert into [Service]   values ('algorithm', 'Curabitur in libero ut massa volutpat convallis.');
insert into [Service]   values ('matrix', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into [Service]   values ('methodology', 'Morbi non quam nec dui luctus rutrum.');
insert into [Service]   values ('matrix', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into [Service]   values ('homogeneous', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into [Service]   values ('groupware', 'Nulla nisl.');
insert into [Service]   values ('circuit', 'Integer non velit.');
insert into [Service]   values ('algorithm', 'Nam nulla.');
insert into [Service]   values ('structure', 'Sed sagittis.');
insert into [Service]   values ('next generation', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into [Service]   values ('challenge', 'Nulla nisl.');
insert into [Service]   values ('Pre-emptive', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into [Service]   values ('Multi-tiered', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into [Service]   values ('asymmetric', 'Duis ac nibh.');
insert into [Service]   values ('intermediate', 'Integer ac neque. Duis bibendum.');
insert into [Service]   values ('Decentralized', 'Donec semper sapien a libero. Nam dui.');
insert into [Service]   values ('project', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into [Service]   values ('dynamic', 'Nulla ac enim.');
insert into [Service]   values ('paradigm', 'Curabitur convallis.');
insert into [Service]   values ('hybrid', 'Nam nulla.');
insert into [Service]   values ('empowering', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into [Service]   values ('Fully-configurable', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into [Service]   values ('Reduced', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into [Service]   values ('algorithm', 'Integer a nibh. In quis justo.');
insert into [Service]   values ('hub', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into [Service]   values ('functionalities', 'Donec dapibus.');